language: python
python:
  - "3.6"
  # PyPy versions

# command to install dependencies .


install:
  - sudo apt-get install xvfb
  - pip3 install xvfbwrapper
  - pip3 install pyqt5
  - pip3 install opencv-python
  - pip3 install requests
  - pip3 install pyinstaller
  - pip3 install --upgrade setuptools
  - sudo apt-get install pylint
  - pip3 install coverage

script:
 - pyinstaller main.py
 - python3 testBuddingWidget.py
 - python3 testEventController.py
 - coverage run --source=buddingWidget testBuddingWidget.py
 - coverage report
 - coverage run --source=buddingController testEventController.py
 - coverage report
#  - pylint ../TYTS
